package FlightSchedulerRobertYan_rjy5060;

import java.sql.Date;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.text.ParseException;
import java.util.ArrayList;
import javax.swing.ImageIcon;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class MainFrame extends javax.swing.JFrame {
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        tabs = new javax.swing.JTabbedPane();
        jPanel1 = new myJPanel("dusty_in_disneys_planes_movie_wide_wallpaper-wide.jpg");
        namelabel = new javax.swing.JLabel();
        nameText = new javax.swing.JTextField();
        flightlabel = new javax.swing.JLabel();
        flightbox = new javax.swing.JComboBox<>();
        daylabel = new javax.swing.JLabel();
        daybox = new javax.swing.JComboBox<>();
        bookbutton = new javax.swing.JButton();
        dialog = new javax.swing.JOptionPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new myJPanel("Airplane-Taking-Off.jpg");
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList(Bookings.getBookingsByDay().toArray());
        jPanel3 = new myJPanel("Dining_and_Shopping.jpg");
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList(WaitList.getWaitList().toArray());
        jPanel4 = new myJPanel("22610665562.png");
        addbutton = new javax.swing.JButton();
        flightnamefield = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        flightseatfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        dayfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        dropfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Jay Jay's Extra Virgin Airlines");
        setPreferredSize(new java.awt.Dimension(900, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 600));

        tabs.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tabsStateChanged(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 600));

        namelabel.setBackground(new java.awt.Color(255, 255, 255));
        namelabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        namelabel.setForeground(new java.awt.Color(255, 204, 0));
        namelabel.setText("Please enter your name:");

        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });

        flightlabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        flightlabel.setForeground(new java.awt.Color(255, 204, 0));
        flightlabel.setText("Flight:");

        flightbox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlights().toArray()));

        daylabel.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        daylabel.setForeground(new java.awt.Color(255, 204, 0));
        daylabel.setText("Day:");

        daybox.setModel(new javax.swing.DefaultComboBoxModel(Days.getDates().toArray()));

        bookbutton.setBackground(new java.awt.Color(255, 204, 0));
        bookbutton.setFont(new java.awt.Font("Broadway", 3, 24)); // NOI18N
        bookbutton.setText("BOOK");
        bookbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookbuttonActionPerformed(evt);
            }
        });

        dialog.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentHidden(java.awt.event.ComponentEvent evt) {
                dialogComponentHidden(evt);
            }
        });

        jButton1.setText("Status by Day");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Waiting Status by Day");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Status by Customer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Eras Demi ITC", 0, 16)); // NOI18N
        jButton4.setText("CANCEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(namelabel)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(flightlabel)
                                .addGap(105, 105, 105)
                                .addComponent(daylabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(flightbox, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(daybox, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(80, 80, 80))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(flightlabel)
                            .addComponent(daylabel)
                            .addComponent(namelabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(flightbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(daybox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(577, 577, 577))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(82, 82, 82)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(bookbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(dialog, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tabs.addTab("Signup", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 600));

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Bookings.getBookingsByDay().toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        tabs.addTab("Booked", jPanel2);

        jPanel3.setPreferredSize(new java.awt.Dimension(900, 600));

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = WaitList.getWaitList().toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        tabs.addTab("Waiting", jPanel3);

        addbutton.setText("Add Flight");
        addbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Old Flight");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setText("Seats");

        dayfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dayfieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("New Day: Hit Enter to submit");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("New Flight");

        jButton5.setText("DROP FLIGHT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(flightnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dropfield, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(flightseatfield, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(addbutton))
                                    .addComponent(jLabel2))
                                .addGap(115, 115, 115)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(dayfield, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton5)))))
                .addContainerGap(148, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flightnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(flightseatfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addbutton)
                    .addComponent(dayfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dropfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addContainerGap(451, Short.MAX_VALUE))
        );

        tabs.addTab("Admin", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameTextActionPerformed
        // TODO add your handling code here: 
    }//GEN-LAST:event_nameTextActionPerformed

    private void bookbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookbuttonActionPerformed
        // TODO add your handling code here: Convert into appropiate values
        if (nameText.getText().equals(""))
            dialog.showMessageDialog(this, "Please enter a name");
            
        else{
            
        Customer c = new Customer(nameText.getText());
        Flights f = new Flights(flightbox.getSelectedItem().toString()); 
        
        Date d = Date.valueOf(daybox.getSelectedItem().toString());
        Days day = new Days(d);
        
        Bookings b = new Bookings(c, f, day, new Timestamp(System.currentTimeMillis()));
        
        
        int result=Bookings.insertBooking(b,0);
        if(result==0){//if good book
            tabs.setSelectedIndex(1);
            dialog.showMessageDialog(this, "You have successfully booked your flight.", "Booking Successful", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
        }
        if(result==1){//if good wait
            tabs.setSelectedIndex(2);
            dialog.showMessageDialog(this, "You have been put on a waitlist.", "WaitList Successful", dialog.INFORMATION_MESSAGE, new ImageIcon("tumblr_m30rap5QLo1r2o2do.png"));
        }
        if(result==2){//if conflict key
            dialog.showMessageDialog(this, "Cannot book for more than one flight", "Booking Error", dialog.INFORMATION_MESSAGE, new ImageIcon("b93.jpg"));
        }
        
        if(result==3){//if flight drop
            dialog.showMessageDialog(this, "A flight has been canceled", "Dropped Flight", dialog.INFORMATION_MESSAGE, new ImageIcon("b93.jpg"));
        }
        
        }
    }//GEN-LAST:event_bookbuttonActionPerformed

    private void dialogComponentHidden(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_dialogComponentHidden
        // TODO add your handling code here:
    }//GEN-LAST:event_dialogComponentHidden

    private void tabsStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tabsStateChanged
        // TODO add your handling code here:
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Bookings.getBookingsByDay().toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = WaitList.getWaitList().toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_tabsStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       String fName = flightbox.getSelectedItem().toString();         
       String dName = daybox.getSelectedItem().toString();
       
       tabs.setSelectedIndex(1);
       
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Bookings.getBookingsByDay(fName, dName).toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
       String dName = daybox.getSelectedItem().toString();
       
       tabs.setSelectedIndex(2);
       
       jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = WaitList.getWaitListStatusbyDay(dName).toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void addbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbuttonActionPerformed
        // TODO add your handling code here:
        String fName = flightnamefield.getText();
        if(flightseatfield.getText().equals(""))
             dialog.showMessageDialog(this, "Make sure to add seats", "Need Seats", dialog.INFORMATION_MESSAGE, new ImageIcon("tumblr_m30rap5QLo1r2o2do.png"));
        else{
        int seats = Integer.parseInt(flightseatfield.getText());
        Flights.addFlight(fName, seats);
        dialog.showMessageDialog(this, fName+" has been added as a new flight with "+seats+" seats.", "Flight added", dialog.INFORMATION_MESSAGE, new ImageIcon("tumblr_m30rap5QLo1r2o2do.png"));
        flightbox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlights().toArray()));
        }
    }//GEN-LAST:event_addbuttonActionPerformed

    private void dayfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dayfieldActionPerformed
        // TODO add your handling code here:       
        //Date temp;   
        try{
           Date temp=java.sql.Date.valueOf(dayfield.getText());
           Days.addDay(temp);
           dialog.showMessageDialog(this, dayfield.getText()+" has been added as a day", "Successful add", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
           daybox.setModel(new javax.swing.DefaultComboBoxModel(Days.getDates().toArray()));
        
        }catch(IllegalArgumentException e){
            dialog.showMessageDialog(this, "Make sure to enter in sql-date format 'year, month, day' (yyyy-MM-dd) ", "Conversion Error", dialog.ERROR_MESSAGE);        
        }
        
       
           
    }//GEN-LAST:event_dayfieldActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String cName = nameText.getText();       
        
       tabs.setSelectedIndex(1);
       
       jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = Customer.getStatus(cName).toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
       
       dialog.showMessageDialog(this, "These are the flights you have registered for.", "Customer Status", dialog.INFORMATION_MESSAGE, new ImageIcon("tumblr_m30rap5QLo1r2o2do.png"));
       
       
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String dropResult;
        String cName = nameText.getText();
        String dName = daybox.getSelectedItem().toString();
        
        dropResult = Bookings.cancelFlight(cName,dName);
        
        if(dropResult=="")
            dialog.showMessageDialog(this, "Cancel Operation successful", "Default", dialog.INFORMATION_MESSAGE, new ImageIcon("tumblr_m30rap5QLo1r2o2do.png"));
        
        if(dropResult=="waitlist")
            dialog.showMessageDialog(this, cName+ " has been dropped from the waitlist for this flight", "Dropped from Waitlist", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
        
        if(dropResult=="bookings")
            dialog.showMessageDialog(this, cName+" has been dropped from the Bookings for this flight", "Dropped from Bookings", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String fName = dropfield.getText();
        ArrayList<String> temp = Bookings.dropFlight(fName);
         flightbox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlights().toArray()));
        
        if(temp==null){
            dialog.showMessageDialog(this, "Not a valid flight to be dropped", "Drop Error", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
            
        }
       if(temp.isEmpty()){
            dialog.showMessageDialog(this, "Rebooking successful", "Rearrange", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
            
        }    
      if(!temp.isEmpty()){
            dialog.showMessageDialog(this, "The following are without wings", "Rearrange", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
            tabs.setSelectedIndex(2);
            flightbox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlights().toArray()));
            jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = temp.toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
            });
        }
        else{
            dialog.showMessageDialog(this, "Drop operation successful", "Default", dialog.INFORMATION_MESSAGE, new ImageIcon("e40.jpg"));
             flightbox.setModel(new javax.swing.DefaultComboBoxModel(Flights.getFlights().toArray()));
            jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = temp.toArray(new String[0]);
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
            });
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addbutton;
    private javax.swing.JButton bookbutton;
    private javax.swing.JComboBox<String> daybox;
    private javax.swing.JTextField dayfield;
    private javax.swing.JLabel daylabel;
    private javax.swing.JOptionPane dialog;
    private javax.swing.JTextField dropfield;
    private javax.swing.JComboBox<String> flightbox;
    private javax.swing.JLabel flightlabel;
    private javax.swing.JTextField flightnamefield;
    private javax.swing.JTextField flightseatfield;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nameText;
    private javax.swing.JLabel namelabel;
    private javax.swing.JTabbedPane tabs;
    // End of variables declaration//GEN-END:variables
}
